# Generated by Django 5.1.5 on 2025-02-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "environments",
            "0001_squashed_0003_alter_environment_id_alter_environmentproject_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
