# Generated by Django 5.2.4 on 2025-07-31 08:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_squashed_0010_alter_notification_issues"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrecipient",
            name="tags_to_add",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="List of additional tags to include in the alert",
                null=True,
                size=None,
            ),
        ),
    ]
