# Generated by Django 5.2.4 on 2025-07-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_squashed_0010_alter_notification_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecipient',
            name='tags_to_add',
            field=models.JSONField(blank=True, default=list, help_text='List of additional tags to include in the alert'),
        ),
    ]
