# Generated by Django 5.2.4 on 2025-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('alerts', '0011_alertrecipient_metadata_fields'), ('alerts', '0012_alertrecipient_tags_to_add')]

    dependencies = [
        ('alerts', '0001_squashed_0010_alter_notification_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecipient',
            name='metadata_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of metadata fields to include in the alert'),
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='tags_to_add',
            field=models.JSONField(blank=True, default=list, help_text='List of additional tags to include in the alert'),
        ),
    ]
