# Generated by Django 5.0.6 on 2024-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_auto_20240318_1449"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectkey",
            old_name="label",
            new_name="name",
        ),
        migrations.AddField(
            model_name="projectkey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
