# Generated by Django 5.1.5 on 2025-01-25 17:33
from django.db import migrations
from django.db.migrations import RunSQL
from apps.shared.migration_utils import get_sql_content


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_rename_label_projectkey_name_projectkey_is_active"),
    ]

    operations = [
        RunSQL(
            sql=get_sql_content(__file__, "get_project_auth_info.sql"),
            reverse_sql="DROP FUNCTION IF EXISTS get_project_auth_info(INTEGER, UUID);",
        )
    ]
