# Generated by Django 5.1.5 on 2025-01-25 17:33
import os

from django.db import migrations
from django.db.migrations import RunSQL


def get_sql_content(filename):
    """Helper to read SQL from a file."""
    sql_dir = os.path.join(os.path.dirname(__file__), "./sql")
    file_path = os.path.join(sql_dir, filename)
    with open(file_path, "r") as f:
        return f.read()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_rename_label_projectkey_name_projectkey_is_active"),
    ]

    operations = [
        RunSQL(
            sql=get_sql_content("get_project_auth_info.sql"),
            reverse_sql="DROP FUNCTION IF EXISTS get_project_auth_info(INTEGER, UUID);",
        )
    ]
