# Generated by Django 5.1.5 on 2025-01-25 17:33
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_rename_label_projectkey_name_projectkey_is_active"),
    ]

    operations = []
