# Generated by Django 5.2.3 on 2025-06-27 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_squashed_0016_auto_20250125_1733"),
    ]

    operations = []
