# Generated by Django 5.2.8 on 2025-11-17 21:29

from django.db import migrations
from django.db.migrations import RunSQL
from apps.shared.migration_utils import get_sql_content


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20250627_1413'),
    ]

    operations = [
        RunSQL(
            sql=get_sql_content(__file__, "get_project_auth_info.sql"),
            reverse_sql="DROP FUNCTION IF EXISTS get_project_auth_info(INTEGER, UUID);",
        )
    ]
