# Generated by Django 5.2.1 on 2025-05-27 22:04

from django.db import migrations
from django.db.migrations import RunSQL
from apps.shared.migration_utils import get_sql_content


class Migration(migrations.Migration):
    dependencies = [
        ("issue_events", "0002_issueevent_hashes_and_more"),
    ]

    operations = [
    ]
