# Generated by Django 5.2.1 on 2025-05-27 22:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue_events", "0002_issueevent_hashes_and_more"),
    ]

    operations = []
