# Generated by Django 5.2.3 on 2025-06-26 16:30

import django.db.models.deletion
import psql_partition.backend.migrations.operations.add_default_partition
import psql_partition.backend.migrations.operations.create_partitioned_model
import psql_partition.manager.manager
import psql_partition.models.partitioned
import psql_partition.types
from django.db import migrations, models

from glitchtip.model_utils import TestDefaultPartition


class Migration(migrations.Migration):
    dependencies = [
        ("issue_events", "0003_auto_20250527_2204"),
        ("organizations_ext", "0009_organization_stripe_primary_subscription"),
    ]

    operations = [
        psql_partition.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name="IssueAggregate",
            fields=[
                ("date", models.DateTimeField()),
                ("count", models.PositiveIntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "issue",
                        "organization",
                        "date",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issue_events.issue",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations_ext.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            partitioning_options={
                "method": psql_partition.types.PostgresPartitioningMethod["RANGE"],
                "key": ["date"],
            },
            bases=(psql_partition.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ("objects", psql_partition.manager.manager.PostgresManager()),
            ],
        ),
        TestDefaultPartition(
            model_name="IssueAggregate",
            name="default",
        ),
    ]
