# Generated by Django 5.2.7 on 2025-10-13 15:39

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue_events", "0004_auto_20250626_1630"),
        ("projects", "0017_auto_20250627_1413"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="issue",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="issue_title_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
