# Generated by Django 5.1.5 on 2025-02-05 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations_ext', '0006_organization_stripe_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('stripe_id', models.CharField(max_length=28, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('events', models.PositiveBigIntegerField()),
                ('is_public', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('stripe_id', models.CharField(max_length=28, primary_key=True, serialize=False)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations_ext.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe.stripeproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
