# Generated by Django 5.1.6 on 2025-02-21 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0007_remove_stripeproduct_price_alter_stripeproduct_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stripesubscription",
            name="unique_primary_subscription_per_organization",
        ),
        migrations.RemoveField(
            model_name="stripesubscription",
            name="is_primary",
        ),
    ]
