# Generated by Django 5.1.6 on 2025-02-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0008_remove_stripesubscription_unique_primary_subscription_per_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesubscription',
            name='product',
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='stripe.stripeprice'),
            preserve_default=False,
        ),
    ]
