# Generated by Django 5.1.6 on 2025-02-24 16:46

from django.db import migrations


def migrate_subscription_product_to_price(apps, schema_editor):
    StripeSubscription = apps.get_model("stripe", "StripeSubscription")

    StripeSubscription.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "stripe",
            "0008_remove_stripesubscription_unique_primary_subscription_per_organization_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(migrate_subscription_product_to_price),
    ]
