# Generated by Django 5.1.6 on 2025-02-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0009_remove_stripesubscription_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesubscription',
            name='product',
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='price',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='stripe.stripeprice'),
            preserve_default=False,
        ),
    ]
