# Generated by Django 5.1.7 on 2025-03-11 15:27

from django.db import migrations, models

from ..constants import SubscriptionStatus


def migrate_active_subscription_statuses(apps, schema_editor):
    StripeSubscription = apps.get_model("stripe", "StripeSubscription")

    StripeSubscription.objects.filter(is_active=True).update(
        status=SubscriptionStatus.ACTIVE
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stripe", "0010_remove_stripesubscription_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("unpaid", "Unpaid"),
                    ("paused", "Paused"),
                ],
                db_index=True,
                max_length=18,
                null=True,
            ),
        ),
        migrations.RunPython(migrate_active_subscription_statuses),
    ]
