# Generated by Django 5.1.7 on 2025-03-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0011_stripesubscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesubscription',
            name='is_active',
        ),
    ]
