# Generated by Django 5.1.7 on 2025-03-12 15:25

from django.db import migrations, models
from django.db.models import F


def migrate_subscription_start_date(apps, schema_editor):
    StripeSubscription = apps.get_model("stripe", "StripeSubscription")

    StripeSubscription.objects.all().update(start_date=F("created"))


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0012_remove_stripesubscription_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscription",
            name="collection_method",
            field=models.CharField(
                choices=[
                    ("charge_automatically", "Charge Automatically"),
                    ("send_invoice", "Send Invoice"),
                ],
                default="charge_automatically",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(migrate_subscription_start_date),
        migrations.AlterField(
            model_name="stripesubscription",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
