# Generated by Django 5.2.4 on 2025-07-04 14:25

import uuid
import django
from django.db import migrations, models
import psql_partition.backend.migrations.operations.add_default_partition
import psql_partition.backend.migrations.operations.create_partitioned_model
import psql_partition.manager.manager
import psql_partition.models.partitioned
import psql_partition.types
from glitchtip.model_utils import TestDefaultPartition


class Migration(migrations.Migration):
    dependencies = [
        ("organizations_ext", "0010_alter_organization_id"),
        ("performance", "0001_squashed_0014_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiongroup",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel("transactionevent"),
        psql_partition.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name="TransactionEvent",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "event_id",
                        "organization",
                        "start_timestamp",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("trace_id", models.UUIDField(db_index=True)),
                (
                    "start_timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Datetime reported by client as the time the measurement started",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datetime reported by client as the time the measurement finished",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Milliseconds"
                    ),
                ),
                (
                    "data",
                    models.JSONField(help_text="General event data that is searchable"),
                ),
                ("tags", models.JSONField(default=dict)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="performance.transactiongroup",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations_ext.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_timestamp"],
            },
            partitioning_options={
                "method": psql_partition.types.PostgresPartitioningMethod["RANGE"],
                "key": ["start_timestamp"],
            },
            bases=(psql_partition.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ("objects", psql_partition.manager.manager.PostgresManager()),
            ],
        ),
        psql_partition.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name="TransactionEvent",
            name="default",
        ),
        psql_partition.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name="TransactionGroupAggregate",
            fields=[
                ("date", models.DateTimeField()),
                ("count", models.PositiveIntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "group",
                        "organization",
                        "date",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_duration",
                    models.FloatField(
                        default=0.0,
                        help_text="Sum of all transaction durations (in ms) for calculating the mean.",
                    ),
                ),
                (
                    "sum_of_squares_duration",
                    models.FloatField(
                        default=0.0,
                        help_text="Sum of squares of durations, for calculating standard deviation.",
                    ),
                ),
                (
                    "histogram",
                    models.JSONField(
                        default=dict,
                        help_text="Stores a fixed-bucket histogram for percentile approximation.",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="performance.transactiongroup",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations_ext.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            partitioning_options={
                "method": psql_partition.types.PostgresPartitioningMethod["RANGE"],
                "key": ["date"],
            },
            bases=(psql_partition.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ("objects", psql_partition.manager.manager.PostgresManager()),
            ],
        ),
        TestDefaultPartition(
            model_name="TransactionGroupAggregate",
            name="default",
        ),
    ]
