# Generated by Django 5.2.4 on 2025-07-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performance", "0016_alter_transactiongroup_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionevent",
            name="duration",
        ),
        migrations.AlterField(
            model_name="transactiongroupaggregate",
            name="sum_of_squares_duration",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Sum of squares of durations, for calculating standard deviation.",
            ),
        ),
        migrations.AlterField(
            model_name="transactiongroupaggregate",
            name="total_duration",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Sum of all transaction durations (in ms) for calculating the mean.",
            ),
        ),
    ]
