# Generated by Django 5.1.2 on 2024-10-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe_ext', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionQuotaWarning',
        ),
    ]
