# Generated by Django 5.0.7 on 2024-07-27 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_email"),
    ]

    operations = []
