# Generated by Django 5.1.3 on 2024-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0009_alter_file_size"),
        ("releases", "0005_alter_releasefile_unique_together_and_more"),
        ("sourcecode", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="files",
            field=models.ManyToManyField(
                through="sourcecode.DebugSymbolBundle", to="files.file"
            ),
        ),
        migrations.DeleteModel(
            name="ReleaseFile",
        ),
    ]
