# Generated by Django 5.1.6 on 2025-02-10 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations_ext", "0006_organizationsocialapp"),
        (
            "organizations_ext",
            "0007_rename_stripe_subscription_id_organization_stripe_customer_id",
        ),
    ]

    operations = []
