# Generated by Django 5.2.3 on 2025-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations_ext", "0009_organization_stripe_primary_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
