# Generated by Django 5.0.6 on 2024-05-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0008_alter_file_type_alter_fileblob_blob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
