# Generated by Django 5.1.3 on 2024-11-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='debug_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Association between file and source code', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='last_used',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
